[book]
authors = ["Doug Bradshaw"]
language = "en"
multilingual = false
src = "src"
title = "Red and Orange: An MdBook Classy Preprocessor Example"

[preprocessor.classy]
command = "../../target/debug/mdbook-classy"