# refer to the original template if further configuraiton is required
# https://github.com/EmbarkStudios/cargo-deny/blob/main/deny.template.toml

# targets that mdbook targets
targets = [
  {triple = "aarch64-unknown-linux-musl"},
  {triple = "x86_64-unknown-linux-gnu"},
  {triple = "x86_64-unknown-linux-musl"},
  {triple = "x86_64-apple-darwin"},
  {triple = "x86_64-pc-windows-msvc"},
]

# This section is considered when running `cargo deny check advisories`
# More documentation for the advisories section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html
[advisories]
ignore = [] 
notice = "deny" 
unmaintained = "warn" 
vulnerability = "deny" 
yanked = "deny" # yanked crates are yanked for a reason

# This section is considered when running `cargo deny check licenses`
# More documentation for the licenses section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
unlicensed = "deny"

# List of explicitly allowed licenses
# See https://spdx.org/licenses/ for list of possible licenses
# Add any of the following as required. These are acceptable, but are not currenlyt in the dependecy graph. 
# "Apache-2.0 WITH LLVM-exception", "BSD-3-Clause", "OpenSSL", 
allow = [
  "MIT",
  "Apache-2.0",
  "Unicode-DFS-2016",
  "CC0-1.0",
  "ISC",
  "MPL-2.0",
]

# Lint level for licenses considered copyleft
allow-osi-fsf-free = "neither"
copyleft = "deny"

# Lint level used when no other predicates are matched
# 1. License isn't in the allow or deny lists
# 2. License isn't copyleft
# 3. License isn't OSI/FSF, or allow-osi-fsf-free = "neither"
default = "deny"
# The confidence threshold for detecting a license from license text.
# [possible values: any between 0.0 and 1.0].
confidence-threshold = 0.95
